
server:
  port: 8000

spring:
  datasource:
    url: jdbc:h2:mem:devdb;NON_KEYWORDS=USER;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

jwt:
  token:
    expiration: 1000000000
    secret: spring-jwt-2023
