
server:
  port: 8000
  error:
    include-stacktrace: never

spring:
  doc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui
  datasource:
    url: jdbc:h2:mem:devdb;NON_KEYWORDS=USER;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      data-locations: classpath:data.sql

jwt:
  token:
    expiration: 300000 # 5min
    # https://passwordsgenerator.net/
    secret: cY%^U+Ku6s~k@EeJ,f;x9p]y*PX3TR{} 
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
      boot:
         autoconfigure: INFO
