
server:
  port: 8000
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:h2:mem:devdb;NON_KEYWORDS=USER;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      data-locations: classpath:data.sql

jwt:
  token:
    expiration: 300000 # 5min
    secret: spring-jwt-2023
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
#       boot:
#          autoconfigure: DEBUG
