@host=http://localhost:8000


### Lista todas as funções
GET {{host}}/roles HTTP/1.1


### Cria uma nova função
POST {{host}}/roles HTTP/1.1
Content-Type: application/json

{
    "name": "MODERATOR"
}